name = "9seki-api"
main = "workers/index.ts"
compatibility_date = "2026-04-16"

[[d1_databases]]
binding = "DB"
database_name = "9seki-db"
database_id = "b3b4538f-8ee1-4968-adfe-da3c75c83d3e"

[[r2_buckets]]
binding = "DATA"
bucket_name = "9seki-data"
